// ─── Complete LIC Plans Database (Official Plans as of 2025-26) ───────────────

export type PlanCategory = 'term' | 'endowment' | 'moneyback' | 'pension' | 'ulip' | 'children' | 'health' | 'whole-life';

export interface LICPlan {
  id: string;
  planNo: string;
  name: string;
  category: PlanCategory;
  tagline: string;
  description: string;
  features: string[];
  minSumAssured: string;
  maxSumAssured: string;
  policyTerm: string;
  premiumTerm: string;
  entryAge: string;
  maturityAge: string;
  maturityBenefit: string;
  deathBenefit: string;
  taxBenefit: string;
  loanFacility: boolean;
  surrenderValue: boolean;
  bonuses: boolean;
  tag?: string; // "Popular" | "New" | "Recommended" etc
  startingPremium: string;
}

export const LIC_PLANS: LICPlan[] = [
  // ── TERM PLANS ─────────────────────────────────────────────
  {
    id: 'jeevan-amar',
    planNo: '855',
    name: 'Jeevan Amar',
    category: 'term',
    tagline: 'Pure life protection at affordable premiums',
    description: 'LIC\'s Jeevan Amar is a non-linked, non-participating individual pure risk premium life insurance plan. It offers high life cover at low premiums.',
    features: [
      'Level Sum Assured or Increasing Sum Assured option',
      'Special rates for women & non-tobacco users',
      'Riders: Accident Benefit, Disability Benefit',
      'Online & offline purchase available',
      'Accidental death benefit rider available',
    ],
    minSumAssured: '₹25 Lakhs',
    maxSumAssured: 'No limit',
    policyTerm: '10 – 40 years',
    premiumTerm: 'Regular / Single / Limited (5 or 10 years)',
    entryAge: '18 – 65 years',
    maturityAge: 'Up to 80 years',
    maturityBenefit: 'No maturity benefit (pure term)',
    deathBenefit: 'Full Sum Assured paid to nominee',
    taxBenefit: 'Section 80C & 10(10D)',
    loanFacility: false,
    surrenderValue: false,
    bonuses: false,
    tag: 'Popular',
    startingPremium: '₹635/month',
  },
  {
    id: 'tech-term',
    planNo: '854',
    name: 'Tech Term',
    category: 'term',
    tagline: 'Affordable online term plan with high cover',
    description: 'LIC\'s Tech Term is an online non-linked, non-participating individual pure risk premium plan exclusively available through LIC\'s website.',
    features: [
      'Exclusively online – lower premiums than offline term',
      'Level or Increasing cover option',
      'Special rates for non-tobacco users',
      'Accidental death benefit option',
      'Smooth online medical process',
    ],
    minSumAssured: '₹50 Lakhs',
    maxSumAssured: 'No limit',
    policyTerm: '10 – 40 years',
    premiumTerm: 'Regular / Single / 5 years / 10 years',
    entryAge: '18 – 65 years',
    maturityAge: 'Up to 80 years',
    maturityBenefit: 'No maturity benefit',
    deathBenefit: 'Sum Assured on death',
    taxBenefit: 'Section 80C & 10(10D)',
    loanFacility: false,
    surrenderValue: false,
    bonuses: false,
    tag: 'Online',
    startingPremium: '₹490/month',
  },
  {
    id: 'saral-jeevan-bima',
    planNo: '827',
    name: 'Saral Jeevan Bima',
    category: 'term',
    tagline: 'Simple term plan with minimal documentation',
    description: 'A simple, standard term life insurance product with simple features offering life cover without any complications.',
    features: [
      'Standard simple term plan',
      'No riders or options – easy to understand',
      'Suitable for first-time insurance buyers',
      'No medical test up to certain limits',
    ],
    minSumAssured: '₹5 Lakhs',
    maxSumAssured: '₹25 Lakhs',
    policyTerm: '5 – 40 years',
    premiumTerm: 'Regular / Limited / Single',
    entryAge: '18 – 65 years',
    maturityAge: 'Up to 70 years',
    maturityBenefit: 'No maturity benefit',
    deathBenefit: 'Sum Assured on death',
    taxBenefit: 'Section 80C',
    loanFacility: false,
    surrenderValue: false,
    bonuses: false,
    startingPremium: '₹350/month',
  },

  // ── ENDOWMENT PLANS ────────────────────────────────────────
  {
    id: 'jeevan-anand',
    planNo: '815',
    name: 'Jeevan Anand',
    category: 'endowment',
    tagline: 'Savings + whole life protection combo',
    description: 'LIC\'s Jeevan Anand is a participating non-linked plan that combines savings with protection. Life cover continues even after maturity.',
    features: [
      'Life cover continues beyond maturity (whole life)',
      'Bonus declared every year',
      'Loan facility available',
      'Accidental Death & Disability Benefit Rider',
      'Maturity + death benefit both payable',
    ],
    minSumAssured: '₹1 Lakh',
    maxSumAssured: 'No limit',
    policyTerm: '15 – 35 years',
    premiumTerm: 'Same as policy term',
    entryAge: '18 – 50 years',
    maturityAge: 'Up to 75 years',
    maturityBenefit: 'Sum Assured + Accumulated Bonus + FAB',
    deathBenefit: '125% of SA + Bonuses (till maturity) / SA after maturity',
    taxBenefit: 'Section 80C & 10(10D)',
    loanFacility: true,
    surrenderValue: true,
    bonuses: true,
    tag: 'Popular',
    startingPremium: '₹2,100/month',
  },
  {
    id: 'jeevan-lakshya',
    planNo: '833',
    name: 'Jeevan Lakshya',
    category: 'endowment',
    tagline: 'Savings plan for family\'s future goals',
    description: 'LIC\'s Jeevan Lakshya is designed to provide financial support for the family in case of unfortunate death during the policy term, with assured income benefit.',
    features: [
      '10% of Sum Assured paid every year on death till maturity',
      'Full Sum Assured paid at maturity',
      'Waiver of premium on death',
      'Bonuses accumulate throughout term',
      'Ideal for education/marriage planning',
    ],
    minSumAssured: '₹1 Lakh',
    maxSumAssured: 'No limit',
    policyTerm: '13 – 25 years',
    premiumTerm: 'Policy term minus 3 years',
    entryAge: '18 – 50 years',
    maturityAge: 'Up to 65 years',
    maturityBenefit: 'SA + Bonuses + FAB',
    deathBenefit: '10% SA/year + full SA + bonuses at maturity',
    taxBenefit: 'Section 80C & 10(10D)',
    loanFacility: true,
    surrenderValue: true,
    bonuses: true,
    startingPremium: '₹3,200/month',
  },
  {
    id: 'jeevan-labh',
    planNo: '936',
    name: 'Jeevan Labh',
    category: 'endowment',
    tagline: 'Limited premium – maximum returns',
    description: 'LIC\'s Jeevan Labh is a limited premium paying endowment plan offering combination of protection and savings.',
    features: [
      'Pay premium for shorter period, coverage for full term',
      'Simple reversionary bonus + FAB',
      'Loan available from year 3',
      'Surrender value after 3 years',
      'Accidental rider available',
    ],
    minSumAssured: '₹2 Lakhs',
    maxSumAssured: 'No limit',
    policyTerm: '16, 21, 25 years',
    premiumTerm: '10, 15, 16 years',
    entryAge: '8 – 59 years',
    maturityAge: 'Up to 75 years',
    maturityBenefit: 'SA + Bonuses + FAB',
    deathBenefit: 'SA + Bonuses',
    taxBenefit: 'Section 80C & 10(10D)',
    loanFacility: true,
    surrenderValue: true,
    bonuses: true,
    tag: 'Recommended',
    startingPremium: '₹4,850/year',
  },
  {
    id: 'jeevan-utsav',
    planNo: '871',
    name: 'Jeevan Utsav',
    category: 'whole-life',
    tagline: 'Lifelong income with whole life protection',
    description: 'LIC\'s Jeevan Utsav is a non-linked, non-participating individual whole life savings insurance plan launched in 2023.',
    features: [
      'Guaranteed income after premium payment term',
      'Life cover for whole life (till age 100)',
      'Multiple income options to choose from',
      'Additional benefits via riders',
      'Loan & surrender facility',
    ],
    minSumAssured: '₹5 Lakhs',
    maxSumAssured: 'No limit',
    policyTerm: 'Whole life (up to age 100)',
    premiumTerm: '5 / 6 / 7 / 8 / 9 / 10 years',
    entryAge: '90 days – 65 years',
    maturityAge: '100 years',
    maturityBenefit: 'Guaranteed maturity addition + SA',
    deathBenefit: 'SA + Guaranteed income payable',
    taxBenefit: 'Section 80C & 10(10D)',
    loanFacility: true,
    surrenderValue: true,
    bonuses: false,
    tag: 'New',
    startingPremium: '₹5,500/month',
  },

  // ── MONEY BACK PLANS ───────────────────────────────────────
  {
    id: 'new-money-back-20',
    planNo: '820',
    name: 'New Money Back Plan – 20 Years',
    category: 'moneyback',
    tagline: 'Periodic payouts for 20 years + bonus',
    description: 'LIC\'s New Money Back Plan (20 Years) provides periodic payment of survival benefits along with insurance protection.',
    features: [
      '20% SA paid at 5, 10, 15 years',
      'Full SA + bonuses at maturity (year 20)',
      'Death benefit = SA + accumulated bonuses',
      'Survival benefits tax-free',
      'Loan facility available',
    ],
    minSumAssured: '₹1 Lakh',
    maxSumAssured: 'No limit',
    policyTerm: '20 years',
    premiumTerm: '15 years',
    entryAge: '13 – 50 years',
    maturityAge: 'Up to 70 years',
    maturityBenefit: '40% SA + Bonus + FAB',
    deathBenefit: 'Full SA + Bonuses (regardless of survival benefits paid)',
    taxBenefit: 'Section 80C & 10(10D)',
    loanFacility: true,
    surrenderValue: true,
    bonuses: true,
    tag: 'Popular',
    startingPremium: '₹5,800/year',
  },
  {
    id: 'new-money-back-25',
    planNo: '821',
    name: 'New Money Back Plan – 25 Years',
    category: 'moneyback',
    tagline: 'Periodic payouts every 5 years for 25 years',
    description: 'LIC\'s New Money Back Plan (25 Years) offers survival benefits at regular intervals for those with longer horizon.',
    features: [
      '15% SA at 5 & 10 years, 20% SA at 15 & 20 years',
      'Full SA + bonuses at maturity (year 25)',
      'Death benefit = full SA + bonuses (no deduction)',
      'Ideal for long-term periodic income',
    ],
    minSumAssured: '₹1 Lakh',
    maxSumAssured: 'No limit',
    policyTerm: '25 years',
    premiumTerm: '20 years',
    entryAge: '13 – 45 years',
    maturityAge: 'Up to 70 years',
    maturityBenefit: '40% SA + Bonus + FAB',
    deathBenefit: 'Full SA + Bonuses',
    taxBenefit: 'Section 80C & 10(10D)',
    loanFacility: true,
    surrenderValue: true,
    bonuses: true,
    startingPremium: '₹4,800/year',
  },

  // ── WHOLE LIFE / CHILDREN ─────────────────────────────────
  {
    id: 'jeevan-umang',
    planNo: '945',
    name: 'Jeevan Umang',
    category: 'whole-life',
    tagline: 'Whole life coverage with annual survival payouts',
    description: 'LIC\'s Jeevan Umang is a non-linked, with-profits, individual life assurance plan offering annual surviving benefits from end of premium paying term.',
    features: [
      '8% of SA paid every year after premium term',
      'Life cover throughout till age 100',
      'Maturity benefit at age 100',
      'Bonus accrues throughout term',
      'Loan available from 3rd year',
    ],
    minSumAssured: '₹2 Lakhs',
    maxSumAssured: 'No limit',
    policyTerm: 'Whole life (up to 100)',
    premiumTerm: '15 / 20 / 25 / 30 years',
    entryAge: '90 days – 55 years',
    maturityAge: '100 years',
    maturityBenefit: 'SA + Bonuses + FAB',
    deathBenefit: 'SA + Bonuses + FAB',
    taxBenefit: 'Section 80C & 10(10D)',
    loanFacility: true,
    surrenderValue: true,
    bonuses: true,
    tag: 'Popular',
    startingPremium: '₹11,200/year',
  },
  {
    id: 'jeevan-tarun',
    planNo: '834',
    name: 'Jeevan Tarun',
    category: 'children',
    tagline: 'Child education & marriage planning plan',
    description: 'LIC\'s Jeevan Tarun is a participating plan specifically designed to meet the educational and other needs of growing children.',
    features: [
      'Survival benefits from age 20 to 24',
      'Maturity at age 25',
      'Premium waiver if parent dies',
      'Bonuses accumulate throughout',
      'Flexible survival benefit options',
    ],
    minSumAssured: '₹75,000',
    maxSumAssured: 'No limit',
    policyTerm: '25 minus entry age',
    premiumTerm: '20 minus entry age',
    entryAge: '90 days – 12 years',
    maturityAge: '25 years',
    maturityBenefit: '(100-SB%) SA + Bonuses',
    deathBenefit: 'SA + Bonuses',
    taxBenefit: 'Section 80C & 10(10D)',
    loanFacility: true,
    surrenderValue: true,
    bonuses: true,
    tag: 'Recommended',
    startingPremium: '₹2,400/year',
  },

  // ── PENSION PLANS ──────────────────────────────────────────
  {
    id: 'jeevan-shanti',
    planNo: '850',
    name: 'Jeevan Shanti',
    category: 'pension',
    tagline: 'Guaranteed pension for life – immediate or deferred',
    description: 'LIC\'s Jeevan Shanti is a non-linked, non-participating, individual, single premium, deferred and immediate annuity plan.',
    features: [
      'Immediate or Deferred annuity option',
      '12 annuity options to choose from',
      'Guaranteed income for life',
      'Joint life annuity option available',
      'Return of purchase price on death',
    ],
    minSumAssured: '₹1.5 Lakhs (purchase price)',
    maxSumAssured: 'No limit',
    policyTerm: 'Whole life',
    premiumTerm: 'Single premium',
    entryAge: '30 – 100 years',
    maturityAge: 'Lifetime annuity',
    maturityBenefit: 'Annuity throughout life',
    deathBenefit: 'Return of purchase price (option-based)',
    taxBenefit: 'Section 80CCC & 10(10A)',
    loanFacility: false,
    surrenderValue: true,
    bonuses: false,
    tag: 'Popular',
    startingPremium: '₹1.5 Lakh (single)',
  },
  {
    id: 'jeevan-akshay-vii',
    planNo: '857',
    name: 'Jeevan Akshay VII',
    category: 'pension',
    tagline: 'Immediate annuity with 10 payout options',
    description: 'LIC\'s Jeevan Akshay VII is a non-linked, non-participating, individual, single premium, immediate annuity plan.',
    features: [
      '10 annuity options',
      'Annuity starts immediately',
      'Option to return purchase price on death',
      'Suitable for retirees with lump sum',
      'Tax benefits on purchase price under 80CCC',
    ],
    minSumAssured: '₹1 Lakh (purchase price)',
    maxSumAssured: 'No limit',
    policyTerm: 'Whole life',
    premiumTerm: 'Single premium',
    entryAge: '30 – 100 years',
    maturityAge: 'Lifetime annuity',
    maturityBenefit: 'Annuity for life',
    deathBenefit: 'Depends on option chosen',
    taxBenefit: 'Section 80CCC',
    loanFacility: false,
    surrenderValue: true,
    bonuses: false,
    startingPremium: '₹1 Lakh (single)',
  },

  // ── ULIP / LINKED PLANS ────────────────────────────────────
  {
    id: 'siip',
    planNo: '852',
    name: 'SIIP (Samridhi Plus)',
    category: 'ulip',
    tagline: 'Market-linked returns with life protection',
    description: 'LIC\'s SIIP is a unit-linked, non-participating life insurance plan with limited premium payment options.',
    features: [
      '4 fund options: Bond, Secured, Balanced, Growth',
      'Partial withdrawal from year 6',
      'Loyalty additions from year 6 onwards',
      'Fund switching up to 4 times/year free',
      'Top-up premiums allowed',
    ],
    minSumAssured: '10x annual premium',
    maxSumAssured: 'No limit',
    policyTerm: '10 – 25 years',
    premiumTerm: '5 / 10 years',
    entryAge: '90 days – 60 years',
    maturityAge: 'Up to 75 years',
    maturityBenefit: 'Higher of Fund Value or SA',
    deathBenefit: 'Higher of (Fund Value, 105% of premiums, SA)',
    taxBenefit: 'Section 80C & 10(10D)',
    loanFacility: false,
    surrenderValue: true,
    bonuses: false,
    tag: 'Market Linked',
    startingPremium: '₹30,000/year',
  },

  // ── NEW / SPECIAL PLANS ────────────────────────────────────
  {
    id: 'bima-kavach',
    planNo: '887',
    name: 'Bima Kavach (Plan 887)',
    category: 'term',
    tagline: 'New 2025 term plan with enhanced benefits',
    description: 'LIC\'s latest term insurance plan launched in 2025, offering comprehensive protection with enhanced feature set including critical illness cover option.',
    features: [
      'Critical illness rider now available',
      'Return of premium option',
      'Enhanced accidental death benefit',
      'Waiver of premium on disability',
      'Multiple payout modes for nominees',
    ],
    minSumAssured: '₹50 Lakhs',
    maxSumAssured: 'No limit',
    policyTerm: '10 – 35 years',
    premiumTerm: 'Regular / Limited / Single',
    entryAge: '18 – 65 years',
    maturityAge: 'Up to 80 years',
    maturityBenefit: 'Return of premium option available',
    deathBenefit: 'Full SA with enhanced options',
    taxBenefit: 'Section 80C & 10(10D)',
    loanFacility: false,
    surrenderValue: false,
    bonuses: false,
    tag: 'New 2025',
    startingPremium: '₹800/month',
  },
  {
    id: 'arogya-rakshak',
    planNo: '904',
    name: 'Arogya Rakshak',
    category: 'health',
    tagline: 'Comprehensive health coverage plan',
    description: 'LIC\'s Arogya Rakshak is a non-linked, non-participating, individual health insurance plan providing fixed benefit health cover.',
    features: [
      'Hospitalisation benefit: daily cash',
      'Major surgical benefit cover',
      'Cancer care benefit included',
      'Heart ailment benefit',
      'No pre-medical test up to 45 years',
    ],
    minSumAssured: '₹2 Lakhs (HCB)',
    maxSumAssured: '₹4 Lakhs (HCB)',
    policyTerm: '1 – 20 years',
    premiumTerm: 'Same as policy term',
    entryAge: '18 – 65 years',
    maturityAge: 'Up to 75 years',
    maturityBenefit: 'No maturity benefit',
    deathBenefit: 'No death benefit (health plan)',
    taxBenefit: 'Section 80D',
    loanFacility: false,
    surrenderValue: false,
    bonuses: false,
    tag: 'Health',
    startingPremium: '₹1,200/year',
  },
];

export const PLAN_CATEGORIES = [
  { id: 'all', label: 'All Plans', emoji: '🏛️' },
  { id: 'term', label: 'Term', emoji: '🛡️' },
  { id: 'endowment', label: 'Endowment', emoji: '💎' },
  { id: 'moneyback', label: 'Money Back', emoji: '💰' },
  { id: 'whole-life', label: 'Whole Life', emoji: '♾️' },
  { id: 'pension', label: 'Pension', emoji: '👴' },
  { id: 'ulip', label: 'ULIP', emoji: '📈' },
  { id: 'children', label: 'Children', emoji: '👶' },
  { id: 'health', label: 'Health', emoji: '🏥' },
];

export const CATEGORY_COLORS: Record<string, string> = {
  term: '#C8102E',
  endowment: '#FFB300',
  moneyback: '#22c55e',
  'whole-life': '#8b5cf6',
  pension: '#f97316',
  ulip: '#3b82f6',
  children: '#ec4899',
  health: '#06b6d4',
};
