'use client';
import React, { useRef, useState } from 'react';
import { Download, Share2, Printer, MessageCircle, Mail, X, Check } from 'lucide-react';
import type { CalcResult, CalcInput } from '@/lib/premium-engine';
import { formatINR } from '@/lib/premium-engine';

interface Props {
  result: CalcResult;
  input: CalcInput;
  onClose: () => void;
}

const PLAN_COLORS: Record<string, string> = {
  term: '#3B82F6', endowment: '#C8102E', moneyback: '#F59E0B',
  'whole-life': '#EC4899', children: '#8B5CF6', pension: '#F97316', ulip: '#06B6D4',
};

export default function ReportGenerator({ result, input, onClose }: Props) {
  const reportRef = useRef<HTMLDivElement>(null);
  const [loading, setLoading] = useState<'pdf' | 'img' | null>(null);
  const [done, setDone] = useState<'pdf' | 'img' | null>(null);

  const planColor = PLAN_COLORS[input.planType] || '#C8102E';
  const modeLabel = { annual: 'Yearly', 'half-yearly': 'Half-Yearly', quarterly: 'Quarterly', monthly: 'Monthly' }[input.paymentMode] || 'Monthly';
  const premiumForMode = result.premiumByMode[input.paymentMode as keyof typeof result.premiumByMode] || result.annualPremium;
  const today = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });

  const flash = (type: 'pdf' | 'img') => {
    setDone(type);
    setTimeout(() => setDone(null), 2000);
  };

  const exportPDF = async () => {
    if (!reportRef.current) return;
    setLoading('pdf');
    try {
      const { default: html2canvas } = await import('html2canvas');
      const { default: jsPDF } = await import('jspdf');
      const canvas = await html2canvas(reportRef.current, { scale: 2, useCORS: true, backgroundColor: '#ffffff' });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      const pdfW = pdf.internal.pageSize.getWidth();
      const pdfH = (canvas.height * pdfW) / canvas.width;
      pdf.addImage(imgData, 'PNG', 0, 0, pdfW, Math.min(pdfH, 297));
      pdf.save(`LIC_Premium_Report_${result.planName.replace(/\s/g, '_')}_${Date.now()}.pdf`);
      flash('pdf');
    } catch (e) { console.error(e); }
    setLoading(null);
  };

  const exportImage = async () => {
    if (!reportRef.current) return;
    setLoading('img');
    try {
      const { default: html2canvas } = await import('html2canvas');
      const canvas = await html2canvas(reportRef.current, { scale: 2, useCORS: true, backgroundColor: '#ffffff' });
      const a = document.createElement('a');
      a.href = canvas.toDataURL('image/png');
      a.download = `LIC_Premium_Card_${result.planName.replace(/\s/g, '_')}.png`;
      a.click();
      flash('img');
    } catch (e) { console.error(e); }
    setLoading(null);
  };

  const handlePrint = () => {
    if (!reportRef.current) return;
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(`<html><head><title>LIC Premium Report</title><style>body{margin:0;font-family:Inter,sans-serif}@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}</style></head><body>`);
    win.document.write(reportRef.current.outerHTML);
    win.document.write('</body></html>');
    win.document.close();
    win.focus();
    setTimeout(() => { win.print(); win.close(); }, 500);
  };

  const shareWhatsApp = () => {
    const text = encodeURIComponent(
      `📊 *LIC Premium Report — ${result.planName}*\n\n` +
      `👤 Age: ${input.age} yrs | ${input.gender} | ${input.smoking ? 'Smoker' : 'Non-smoker'}\n` +
      `🎯 Goal: ${input.goal}\n` +
      `💰 Sum Assured: ${formatINR(input.sumAssured)}\n` +
      `📅 Term: ${input.policyTerm} years\n\n` +
      `💳 *Premium: ${formatINR(premiumForMode)} ${modeLabel}*\n` +
      `🏦 Maturity Benefit: ${formatINR(result.maturityBenefit)}\n` +
      `🛡️ Death Benefit: ${formatINR(result.deathBenefit)}\n` +
      `📈 ROI: ~${result.roi}%\n\n` +
      `_Generated by LIC Margadarshi App_`
    );
    window.open(`https://wa.me/?text=${text}`, '_blank');
  };

  const shareEmail = () => {
    const subject = encodeURIComponent(`LIC Premium Report — ${result.planName}`);
    const body = encodeURIComponent(
      `LIC Premium Report\n\nPlan: ${result.planName} (Plan No. ${result.planNo})\n` +
      `Age: ${input.age} | Gender: ${input.gender} | Smoker: ${input.smoking ? 'Yes' : 'No'}\n` +
      `Goal: ${input.goal} | Sum Assured: ${formatINR(input.sumAssured)}\n` +
      `Policy Term: ${input.policyTerm} yrs | Premium Term: ${input.premiumTerm} yrs\n\n` +
      `PREMIUM: ${formatINR(premiumForMode)} (${modeLabel})\n` +
      `Annual Premium: ${formatINR(result.annualPremium)}\n` +
      `Maturity Benefit: ${formatINR(result.maturityBenefit)}\n` +
      `Death Benefit: ${formatINR(result.deathBenefit)}\n` +
      `Bonus Estimate: ${formatINR(result.bonusEstimate)}\n` +
      `Tax Saving/yr: ${formatINR(result.taxSaving)}\n` +
      `Effective ROI: ~${result.roi}%\n\n` +
      `AI Insight: ${result.aiInsight}\n\n` +
      `Generated on ${today} via LIC Margadarshi App`
    );
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  return (
    <div style={{ position: 'fixed', inset: 0, zIndex: 300, display: 'flex', alignItems: 'flex-end', justifyContent: 'center', background: 'rgba(0,0,0,0.6)', backdropFilter: 'blur(10px)' }}
      onClick={onClose}>
      <div onClick={e => e.stopPropagation()} style={{ background: '#fff', borderRadius: '24px 24px 0 0', width: '100%', maxWidth: 600, maxHeight: '95vh', overflowY: 'auto', boxShadow: '0 -16px 60px rgba(0,0,0,0.3)' }}>

        {/* Modal Header */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '18px 20px 12px', position: 'sticky', top: 0, background: '#fff', zIndex: 1, borderBottom: '1px solid #f0f0f0' }}>
          <div>
            <div style={{ fontSize: 16, fontWeight: 800, color: '#111' }}>📄 Export Report</div>
            <div style={{ fontSize: 11, color: '#888', marginTop: 2 }}>Download, print or share your premium summary</div>
          </div>
          <button onClick={onClose} style={{ width: 32, height: 32, borderRadius: '50%', border: '1px solid #e5e7eb', background: '#f9fafb', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', color: '#666' }}>
            <X size={15} />
          </button>
        </div>

        {/* Action Buttons */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2,1fr)', gap: 10, padding: '16px 20px' }}>
          {[
            { label: 'Download PDF', icon: Download, color: '#C8102E', bg: 'rgba(200,16,46,0.08)', border: 'rgba(200,16,46,0.2)', action: exportPDF, key: 'pdf' as const },
            { label: 'Save as Image', icon: Share2, color: '#8B5CF6', bg: 'rgba(139,92,246,0.08)', border: 'rgba(139,92,246,0.2)', action: exportImage, key: 'img' as const },
            { label: 'Print Report', icon: Printer, color: '#3B82F6', bg: 'rgba(59,130,246,0.08)', border: 'rgba(59,130,246,0.2)', action: handlePrint, key: null },
            { label: 'Share WhatsApp', icon: MessageCircle, color: '#22c55e', bg: 'rgba(34,197,94,0.08)', border: 'rgba(34,197,94,0.2)', action: shareWhatsApp, key: null },
            { label: 'Email Report', icon: Mail, color: '#F59E0B', bg: 'rgba(245,158,11,0.08)', border: 'rgba(245,158,11,0.2)', action: shareEmail, key: null },
          ].map((btn) => (
            <button key={btn.label} onClick={btn.action} disabled={loading !== null} style={{
              display: 'flex', alignItems: 'center', gap: 10, padding: '13px 16px', borderRadius: 14,
              border: `1px solid ${btn.border}`, background: btn.bg, cursor: loading ? 'wait' : 'pointer',
              transition: 'all 0.2s', opacity: loading && loading !== btn.key ? 0.6 : 1,
            }}>
              {btn.key && done === btn.key ? <Check size={18} color="#22c55e" /> : btn.key && loading === btn.key
                ? <div style={{ width: 18, height: 18, borderRadius: '50%', border: `2px solid ${btn.color}`, borderTopColor: 'transparent', animation: 'spin 0.6s linear infinite' }} />
                : <btn.icon size={18} color={btn.color} />}
              <span style={{ fontSize: 12, fontWeight: 700, color: '#111' }}>{btn.label}</span>
            </button>
          ))}
        </div>

        <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>

        {/* ── Report Card (what gets exported) ── */}
        <div style={{ padding: '0 20px 24px' }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: '#888', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 12 }}>Preview</div>

          <div ref={reportRef} style={{ background: '#fff', borderRadius: 20, overflow: 'hidden', border: '1px solid #e5e7eb', fontFamily: 'Inter, sans-serif' }}>

            {/* Report Header */}
            <div style={{ background: `linear-gradient(135deg, ${planColor} 0%, #111 100%)`, padding: '28px 24px', position: 'relative', overflow: 'hidden' }}>
              <div style={{ position: 'absolute', top: -30, right: -30, width: 140, height: 140, borderRadius: '50%', background: 'rgba(255,255,255,0.06)' }} />
              <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between' }}>
                <div>
                  <div style={{ fontSize: 10, color: 'rgba(255,255,255,0.55)', fontWeight: 600, letterSpacing: '1.5px', textTransform: 'uppercase', marginBottom: 6 }}>LIC MARGADARSHI</div>
                  <div style={{ fontSize: 22, fontWeight: 900, color: '#fff', lineHeight: 1.2 }}>Premium Report</div>
                  <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.6)', marginTop: 4 }}>{result.planName} · Plan No. {result.planNo}</div>
                </div>
                <div style={{ textAlign: 'right' }}>
                  <div style={{ fontSize: 10, color: 'rgba(255,255,255,0.5)', marginBottom: 2 }}>Generated</div>
                  <div style={{ fontSize: 11, color: '#fff', fontWeight: 600 }}>{today}</div>
                </div>
              </div>
            </div>

            {/* User Details */}
            <div style={{ padding: '16px 24px', background: '#f8f9fa', borderBottom: '1px solid #eee', display: 'flex', gap: 24, flexWrap: 'wrap' }}>
              {[
                { label: 'Age', value: `${input.age} years` },
                { label: 'Gender', value: input.gender.charAt(0).toUpperCase() + input.gender.slice(1) },
                { label: 'Smoker', value: input.smoking ? 'Yes' : 'No' },
                { label: 'Goal', value: input.goal.charAt(0).toUpperCase() + input.goal.slice(1) },
                { label: 'Income', value: formatINR(input.annualIncome) + '/yr' },
              ].map(d => (
                <div key={d.label}>
                  <div style={{ fontSize: 9, color: '#888', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.4px', marginBottom: 2 }}>{d.label}</div>
                  <div style={{ fontSize: 13, fontWeight: 700, color: '#111' }}>{d.value}</div>
                </div>
              ))}
            </div>

            {/* Premium Hero */}
            <div style={{ padding: '24px', background: '#fff' }}>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 20 }}>
                <div style={{ padding: '18px', borderRadius: 14, background: `linear-gradient(135deg, ${planColor}10, ${planColor}05)`, border: `1px solid ${planColor}20` }}>
                  <div style={{ fontSize: 9, color: '#888', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 6 }}>Premium ({modeLabel})</div>
                  <div style={{ fontSize: 26, fontWeight: 900, color: planColor, lineHeight: 1 }}>{formatINR(premiumForMode)}</div>
                  <div style={{ fontSize: 10, color: '#666', marginTop: 4 }}>Annual: {formatINR(result.annualPremium)}</div>
                </div>
                <div style={{ padding: '18px', borderRadius: 14, background: 'linear-gradient(135deg,rgba(16,185,129,0.08),rgba(16,185,129,0.03))', border: '1px solid rgba(16,185,129,0.15)' }}>
                  <div style={{ fontSize: 9, color: '#888', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 6 }}>Maturity Benefit</div>
                  <div style={{ fontSize: 26, fontWeight: 900, color: '#10B981', lineHeight: 1 }}>{formatINR(result.maturityBenefit)}</div>
                  <div style={{ fontSize: 10, color: '#666', marginTop: 4 }}>After {input.policyTerm} years</div>
                </div>
              </div>

              {/* Benefits grid */}
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 10, marginBottom: 20 }}>
                {[
                  { label: 'Death Benefit', value: formatINR(result.deathBenefit), color: '#3B82F6' },
                  { label: 'Bonus Estimate', value: formatINR(result.bonusEstimate), color: '#F59E0B' },
                  { label: 'Tax Saving/yr', value: formatINR(result.taxSaving), color: '#8B5CF6' },
                  { label: 'Total Paid', value: formatINR(result.totalPremiumPaid), color: '#64748B' },
                  { label: 'Surplus Gain', value: formatINR(result.surplusGain), color: '#10B981' },
                  { label: 'Eff. ROI', value: `~${result.roi}%`, color: '#C8102E' },
                ].map(b => (
                  <div key={b.label} style={{ padding: '10px', borderRadius: 10, background: '#f8f9fa', border: '1px solid #eee' }}>
                    <div style={{ fontSize: 8, color: '#888', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.3px', marginBottom: 4 }}>{b.label}</div>
                    <div style={{ fontSize: 13, fontWeight: 800, color: b.color }}>{b.value}</div>
                  </div>
                ))}
              </div>

              {/* Policy Details */}
              <div style={{ borderRadius: 12, border: '1px solid #eee', overflow: 'hidden', marginBottom: 20 }}>
                <div style={{ padding: '10px 16px', background: '#f8f9fa', fontSize: 11, fontWeight: 700, color: '#444', borderBottom: '1px solid #eee' }}>Policy Details</div>
                {[
                  ['Sum Assured', formatINR(input.sumAssured)],
                  ['Policy Term', `${input.policyTerm} years`],
                  ['Premium Term', `${input.premiumTerm} years`],
                  ['Payment Mode', modeLabel],
                  ['Riders', [input.riders.accidentDeath && 'ADB', input.riders.criticalIllness && 'CI', input.riders.waiver && 'PWB'].filter(Boolean).join(', ') || 'None'],
                ].map(([k, v]) => (
                  <div key={k} style={{ display: 'flex', justifyContent: 'space-between', padding: '9px 16px', borderBottom: '1px solid #f5f5f5' }}>
                    <span style={{ fontSize: 12, color: '#666' }}>{k}</span>
                    <span style={{ fontSize: 12, fontWeight: 700, color: '#111' }}>{v}</span>
                  </div>
                ))}
              </div>

              {/* Milestones */}
              {result.projections.length > 0 && (
                <div style={{ marginBottom: 20 }}>
                  <div style={{ fontSize: 11, fontWeight: 700, color: '#444', marginBottom: 10 }}>Growth Milestones</div>
                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 8 }}>
                    {result.projections.filter(p => [5, 10, input.policyTerm].includes(p.year)).map(p => (
                      <div key={p.year} style={{ padding: '10px', borderRadius: 10, background: '#f8f9fa', textAlign: 'center', border: '1px solid #eee' }}>
                        <div style={{ fontSize: 10, fontWeight: 800, color: planColor }}>Year {p.year}</div>
                        <div style={{ fontSize: 11, fontWeight: 700, color: '#111', marginTop: 4 }}>{formatINR(p.deathBenefit)}</div>
                        <div style={{ fontSize: 9, color: '#888' }}>cover</div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* AI Insight */}
              <div style={{ padding: '14px 16px', borderRadius: 12, background: 'linear-gradient(135deg,rgba(139,92,246,0.06),rgba(139,92,246,0.02))', border: '1px solid rgba(139,92,246,0.15)', marginBottom: 16 }}>
                <div style={{ fontSize: 10, fontWeight: 700, color: '#8B5CF6', marginBottom: 6, textTransform: 'uppercase', letterSpacing: '0.5px' }}>✨ AI Insight</div>
                <p style={{ fontSize: 12, color: '#444', lineHeight: 1.65, margin: 0 }}>{result.aiInsight}</p>
              </div>

              {/* Human summary */}
              <div style={{ padding: '14px 16px', borderRadius: 12, background: 'rgba(200,16,46,0.04)', border: '1px solid rgba(200,16,46,0.12)', marginBottom: 20 }}>
                <div style={{ fontSize: 10, fontWeight: 700, color: '#C8102E', marginBottom: 6, textTransform: 'uppercase', letterSpacing: '0.5px' }}>❤️ In Simple Words</div>
                <p style={{ fontSize: 12, color: '#444', lineHeight: 1.65, margin: 0 }}>{result.humanSummary}</p>
              </div>

              {/* Footer */}
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', paddingTop: 16, borderTop: '1px solid #eee' }}>
                <div>
                  <div style={{ fontSize: 12, fontWeight: 800, color: '#C8102E' }}>LIC Margadarshi</div>
                  <div style={{ fontSize: 9, color: '#888' }}>Your Trusted Policy Advisor</div>
                </div>
                <div style={{ textAlign: 'right', fontSize: 9, color: '#bbb' }}>
                  <div>*Estimates based on LIC tabular rates 2025-26</div>
                  <div>Actual benefits may vary. Consult LIC advisor.</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
